### ISSUE TITLE
Not an issue about Merchello...

### ISSUE THREAD

**Issue by schmurtzm** [TRiV07/Merchello#5]
Hi,

Hi @TRiV07 ,
Sorry for this fake issue, I'm trying to contact you about .net HLDS launcher, first I would like to thank you about this little software, it's old but I use it since few days with pleasure :) 

I would like to know if you would accept to publish sources on github ? I know that it is old and that I'm probably the last man on earth who make hlds servers on Windows (:D) but it would be very useful for me and may be others to be able to update it.

Thank you !
Best regards (and again sorry, I don't find any other way to contact you).

**Comment by TRiV07** [comment]
Hi @schmurtzm!
Nice to know that my app still useful so much time :)
I will try to find sources, and think about making it public.

Regards!

**Comment by schmurtzm** [comment]
Great ! 
Thanks for your positive answer, this is very kind ! :grinning:

**Comment by schmurtzm** [comment]
Hi, did you have some time to take a look ? 😄

**Comment by schmurtzm** [comment]
Hi @TRiV07 , sorry to importune again. Just to know if you have the time to look on your old hard drive if you fdind something ;)

Thanks again ;)

**Comment by TRiV07** [comment]
Hi @schmurtzm,
Just uploaded! Look here: [link](https://github.com/TRiV07/.net-Hlds-Launcher)
